# ==============================================================================
# Variables — set via terraform.tfvars (generated by the workflow from GitHub variables)
# ==============================================================================

variable "subscription_id" {
  description = "Azure subscription ID"
  type        = string
  validation {
    condition     = can(regex("^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$", var.subscription_id))
    error_message = "The subscription_id must be a valid UUID."
  }
}

variable "workload" {
  description = "Short workload identifier (e.g. 'runner')"
  type        = string
}

variable "environment" {
  description = "Environment identifier (e.g. 'prod', 'dev')"
  type        = string
}

variable "instance" {
  description = "Instance identifier for uniqueness (e.g. '001')"
  type        = string
}

variable "location" {
  description = "Azure region (e.g. 'westeurope')"
  type        = string
}

variable "github_org" {
  description = "GitHub organization name"
  type        = string
}

variable "github_repo" {
  description = "GitHub repository in 'org/repo' format"
  type        = string
}

variable "github_app_id_secret_name" {
  description = "Key Vault secret name for GitHub App ID"
  type        = string
  default     = "github-app-id"
}

variable "github_app_installation_id_secret_name" {
  description = "Key Vault secret name for GitHub App installation ID"
  type        = string
  default     = "github-app-installation-id"
}

variable "github_app_private_key_secret_name" {
  description = "Key Vault secret name for GitHub App private key PEM"
  type        = string
  default     = "github-app-private-key"
}

variable "runner_workload_roles" {
  description = "Azure roles granted to runner identity at subscription scope"
  type        = list(string)
  default     = []
}
