terraform {
  required_version = ">= 1.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.63"
    }
  }

  # Backend values are injected at runtime via backend.hcl
  # (generated by the deploy workflow from GitHub variables).
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}
